<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: python | just some lazy admins]]></title>
  <link href="http://lazyadmin.me/blog/categories/python/atom.xml" rel="self"/>
  <link href="http://lazyadmin.me/"/>
  <updated>2014-08-13T14:25:01+07:00</updated>
  <id>http://lazyadmin.me/</id>
  <author>
    <name><![CDATA[Thang Pham & Kao Nhan]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[Python: quản lý kết nối MySQL]]></title>
    <link href="http://lazyadmin.me/blog/2014/08/12/python-quan-ly-ket-noi-mysql/"/>
    <updated>2014-08-12T14:08:37+07:00</updated>
    <id>http://lazyadmin.me/blog/2014/08/12/python-quan-ly-ket-noi-mysql</id>
    <content type="html"><![CDATA[<p>Khi sử dụng Python để code 1 vài tool hay script với Mysql,tornado&hellip;. mình hay gặp lỗi &ldquo;Dealing with OperationalError 2006, &lsquo;MySQL server has gone away&rdquo;. Cái này do kết nối giữa mysql
và python bị timeout, lúc gọi lại hàm thì nó chưa được reconnect.Dưới đây là đoạn code đơn giản để bạn <strong>avoid</strong> chuyện đấy:</p>

<pre><code>
import MySQLdb

class DB:
  conn = None

  def connect(self):
    self.conn = MySQLdb.connect()

  def query(self, sql):
    try:
      cursor = self.conn.cursor()
      cursor.execute(sql)
    except (AttributeError, MySQLdb.OperationalError):
      self.connect()
      cursor = self.conn.cursor()
      cursor.execute(sql)
    return cursor

db = DB()
sql = "SELECT * FROM foo"
cur = db.query(sql)
# wait a long time for the Mysql connection to timeout
cur = db.query(sql)
# still works

</code></pre>

]]></content>
  </entry>
  
</feed>
